//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int tagId { get; set; }
        public string tagName { get; set; }
        public int points { get; set; }
        public Nullable<int> songId { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
